

type Event {
    result: String!
}

type petReport {
     email: String!
     phoneNo: String!
     inputOne: String!
     inputTwo: String!
}

type Query {
    getReport : [petReport]
}


type Mutation {
    petForm(name: String!, description: String!): Event!
} 